DEFINE_ACTION_FUNCTION cd_divine_post BEGIN

	INCLUDE "%MOD_FOLDER%/%component_loc%/lib/cdfunctions.tpa"
	

// bgee 2.6 includes this file, even though it's unused, so we patch just in case
COPY_EXISTING ~asumm1x.vvc~ ~override~
  WRITE_ASCII 0x78 ~#eff_m13~
IF_EXISTS

		
  ACTION_IF ((MOD_IS_INSTALLED ~iwdification/setup-iwdification.tp2~ ~120~) AND (FILE_EXISTS ~iwdification/evasion/evasion_divine.2da~)) BEGIN

    INCLUDE ~iwdification/evasion/evasion.tpa~
    LAF cd_add_evasion STR_VAR 2da_file = ~iwdification/evasion/evasion_divine.2da~ END 
  
  END  

  ACTION_IF enhanced_edition BEGIN

    COPY ~%MOD_FOLDER%/%component_loc%/lib/resource/0103.ini~    ~override~ // spiritual wrath animation
         ~%MOD_FOLDER%/%component_loc%/lib/resource/swrathu.bam~ ~override~
         ~%MOD_FOLDER%/%component_loc%/lib/resource/0104.ini~    ~override~ // smashing wave animation
         ~%MOD_FOLDER%/%component_loc%/lib/resource/swavet.bam~  ~override~

    APPEND ~animate.ids~ ~0x0103 SPIRITUAL_WRATH~ UNLESS ~^0x0103~  
    APPEND ~animate.ids~ ~0x0104 SMASHING_WAVE~   UNLESS ~^0x0104~ 

  END 
       
END